### ISSUE TITLE
Create default .gitignore

### ISSUE THREAD

**Issue by mslinn** [softprops/np#2]
How about having np create a default `.gitignore` when creating a new SBT project? Here is what I usually put in `.gitignore`:

```
.cache
/server.conf
/project/boot
/project/project
/project/target
/target
/.idea
/.idea_modules
/lib
*~
```

**Comment by softprops** [comment]
Sounds cool. I end up doing the same if the project is goes anywhere. I will probably just default to git ignoring sbt specific artifacts and provide a way to override for ide specific stuff. Thanks for pointing this out.

**Comment by mslinn** [comment]
Probably the easiest thing to do, if you don't want to enable all the entries, is to provide them all but comment some of them out. It's easier to uncomment than to remember what you want and type them in, or to paste from another project.

**Comment by Blaisorblade** [comment]
Note that some of those belong in a global gitignore (like `*~`).

**Comment by Sciss** [comment]
This is my default `.gitignore`, perhaps something along these lines is useful:

```
lib_managed/
src_managed/
project/boot/
.idea/
.idea_modules/
```

(There are probably similar ideas if you use Eclipse or Netbeans)

**Comment by Blaisorblade** [comment]
I think `src_managed/` and `project/boot/` were created only by SBT 0.7 (src_managed now lives in `target`). `lib_managed` is not created by default.

**Comment by Sciss** [comment]
I think you are right about `src_managed` and `project/boot`. I always have `lib_managed` as I prefer to use `retrieveManaged := true`. It would be great to include this. It doesn't hurt anyone who doesn't have that folder, but it's a standard managed sbt folder which should not be included in a repository.

**Comment by grossws** [comment]
I think, IDE-specific or system-specific things should be in global gitignore. I has something like

```
*.iml
.idea/
*~
.*.swp
```

in separate file `~/.gitignore_global` and set `core.excludesfile` to `/home/gross/.gitignore_global` (with `git config --global core.excludesfile /home/gross/.gitignore_global`).

Project-local `.gitignore` should usually have maven/sbt-specific things like `target/`, `project/target/` or `project/project/` things.
