### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by gmosx** [softprops/np#3]
I followed the instructions, i.e added:

resolvers += "lessis" at "http://repo.lessis.me"

addSbtPlugin("me.lessis" % "np" % "0.2.0")

seq(npSettings: _*)

to 

~/.sbt/plugins/build.sbt

but when running sbt, I get the following error:

/home/gmosx/.sbt/plugins/build.sbt:5: error: not found: value npSettings
seq(npSettings: _*)
    ^
[error] Type error in expression

Any ideas?

**Comment by softprops** [comment]
I think you might have misread that. `plugins/build.sbt` is a _plugin_ definition. You install plugins by calling `addSbtPlugin` and adding what ever resolvers plugins require. 

You configure sbt plugins in _build_ definitions. Plugin settings are made available to build definitions but not plugin definitions. The way you define a global build definition is by placing a `.sbt` file under `~/.sbt`, the the plugins directory.

The example in the readme references a `~/.sbt/np.sbt` but really you can call the file what ever you want as long as it ends with `.sbt`.  Let me know if that helps.

**Comment by ghost** [comment]
I experienced the same issue as gmosx. Shall I create a fork in order to make this more clearer?

**Comment by softprops** [comment]
When dealing with this kinds of things it's very helpful for me know know what version of sbt you are using before I can point you in the right direction. Versioning schemes have historically been different across sbt plugins when it comes to publishing binary artifacts. Can you tell me which version of sbt you are using.

**Comment by ghost** [comment]
My understanding of the issue is 'seq(npSettings: __)' was in .sbt/plugins/build.sbt and not .sbt/_.sbt.

**Comment by pohl** [comment]
I suggest the language in the directions be improved.  In particular, the phrase:

```
"Doing this in a global .sbt file under ~/.sbt will..."
```

...is likely to be interpreted, by people from the unix tradition, as guidance to create an invisible file called ".sbt" in the invisible directory "~/.sbt", yielding the path ~/.sbt/.sbt

I get the impression that the phrase actually intended to guide the installer towards creating some foo.sbt file in that directory.

It is no the case that "you can call the file anything you want as long as it ends with .sbt".  After all ".sbt" ends with ".sbt" (the degenerate case) and it will not work.  There needs to be some non-empty string preceding the "."

**Comment by v6ak** [comment]
I agree that README is a bit confusing. Code `seq(npSettings: _*)` should be in `~/.sbt/build.sbt`

**Comment by cocodrino** [comment]
sorry I'm having the same issue...where I need past the code?..I write it in;
/home/me/.sbt/0.13/ 
inside a file *.sbt (first I use build.sbt and then I change to np.sbt)

the code:

```
 addSbtPlugin("me.lessis" % "np" % "0.2.0")

resolvers += Resolver.url("sbt-plugin-releases",
   url("http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/"))(
   Resolver.ivyStylePatterns)
```

when I run sbt I get

```
module not found: me.lessis#np;0.2.0
sbt.ResolveException: unresolved dependency: me.lessis#np;0.2.0: not found
```

I'm pretty bad using sbt ("simple" build tool)...so I don't know if I did a mistake...

**Comment by softprops** [comment]
It's not you, it's me. I forgot to publish this one for sbt 0.13 #blamedoug :) Anyway it's up there now

I tested this with sbt's new 0.13 global settings placement. I added some new docs [here](https://github.com/softprops/np#for-sbt-013) and noted some shell syntax changes [here](https://github.com/softprops/np#settings) Let me know if you run into other issues.

**Comment by softprops** [comment]
to help avoid more installation confusion Ill probably take down the 0.12 instructions once sbt 0.13 is and and final.

**Comment by 123avi** [comment]
I am getting the same issue 
sbt.ResolveException: unresolved dependency: me.lessis#np;0.2.0: not found

also when putting this seq(npSettings: __) under progect/.sbt/build.sbt I am getting 
seq(npSettings: __)
    ^
[error] Type error in expression

**Comment by HerringtonDarkholme** [comment]
from the README

> If you wish to globally mix in npSettings, create a file under ~/.sbt/0.13 called np.sbt ( it doesn't    matter what you call this either ) containing the line ...

Maybe this sentence does not make itself understood, at least to new comer like me. 
A more practical description could be : 'If you wish to use `np` as a command in all  sbt sessions, create a file under ~/.sbt/0.13 called np.sbt ( it doesn't    matter what you call this either ) containing the line ...'

It's clear and oriented at users' intention. Users are exempt from groking the difference between _plugin definition_ and _build definition_
