### ISSUE TITLE
copy in settings from a template

### ISSUE THREAD

**Issue by paulp** [softprops/np#4]
I would find this more useful if I could point it at a file with settings to be copied into all new projects.  (I am super averse to global settings since until I partitioned sbt versions from one another they always broke, and even with that out of the way they create project fragility.)

**Comment by softprops** [comment]
Cool. I'll have to talk to @n8han about how that overlaps with [giter8](https://github.com/n8han/giter8#readme). What I mainly wanted was something that I can use to quickly get started without boiler plate so right now its the bare minimum and doesn't use templates (remote or local). giter8 allows you to share template which you can use once hosted on github. np allows you do generate structures within a project even after the first time you run it. Maybe I can talk to nathan about a local giter8 templates. He already has it pretty well factored out.

**Comment by arosien** [comment]
local g8 templates would be awesome!
